
name: Build on tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '15'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@worksbutnottested'

    - name: Download dependencies
      run: |
        npm install

    - name: Build managed package
      run: |
        npm run build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save log file from managed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: npm-log-managed-build
        path: /home/runner/.npm/_logs

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
